# -------------------------------------------------------------------------------------
# Permalinks Configuration
# See: https://gohugo.io/content-management/urls/#permalinks
# -------------------------------------------------------------------------------------

posts = ":year/:month/:day/:filename"
# posts = "posts/:slugorfilename"
